services:
  postgres:
    image: postgres:15
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app_demo
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4 
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"